name: CI Cache Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: prime-cache-cef01b2
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: cache-cef01b2-${{ runner.os }}
          restore-keys: cache-cef01b2-

      - name: Echo cache result
        run: echo "Cache hit = ${{ steps.cache.outputs.cache-hit }}"

      - name: Dummy build
        run: echo "✅ Build completed successfully."
