name: Email Step Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 24f2006848@ds.study.iitm.ac.in
        run: echo "Hello, world!"
